<div style="text-align:justify">
	<h3>Notificaci&oacute;n de Condiciones de Uso y Poltica de Privacidad del Servicio "Oficina Virtual" de la Direcci&oacute;n de Rentas Municipales de la Alcalda del Municipio Sucre</h3>
	<p>

		Este servicio constituye una materializaci&oacute;n de los principios y fundamentos consagrados en el Decreto-Ley No. 386 sobre Simplificaci&oacute;n de Tr&aacute;mites Administrativos de fecha 05 de octubre de 1999, publicado en Gaceta Oficial de la Repblica de Venezuela No. 5.393 Extraordinario de fecha 22 de octubre de 1999, y en el Decreto No. 825 de fecha 10 de mayo de 2000, publicado en Gaceta Oficial de la Rep&uacute;blica Bolivariana de Venezuela No. 36.955 de fecha 22 mayo de 2000, referente al acceso y uso de Internet como pol&iacute;tica prioritaria del Estado Venezolano y, en especial, representa un paso m&aacute;s en el proceso de modernizaci&oacute;n del sistema tributario del Municipio Sucre del Estado Miranda, en lo sucesivo EL MUNICIPIO; el cumplimiento de lo establecido en los artculos 125 y 139 del C&oacute;digo Org&aacute;nico Tributario y la aplicaci&oacute;n de lo previsto en los artculos 64 y 71 de la Ordenanza sobre Actividades Econ&oacute;micas de Industria, Comercio, Servicios o de &iacute;ndole Similar.
		Al registrarse en el servicio "Oficina Virtual", EL USUARIO acepta las condiciones y t&eacute;rminos expuestos en este documento, y en se&ntilde;al de aceptaci&oacute;n debe seleccionar la casilla respectiva al pie de este documento.
		EL MUNICIPIO se interesa en la seguridad de la informaci&oacute;n y de los datos suministrados por nuestros usuarios a trav&eacute;s del servicio "Oficina Virtual", por ello recomendamos la lectura acuciosa de las normas contenidas en esta p&aacute;gina, las cuales explican la forma en que dichos datos e informaci&oacute;n son utilizados, y qu&eacute; destino tiene la informaci&oacute;n personal (correspondiente a persona natural o jur&iacute;dica) que se registra en nuestra base de datos. <br/><br/>

		Estas normas, por el af&iacute;n de mejorar nuestros servicios y la seguridad de nuestros usuarios, pueden ser objeto de modificaciones, raz&oacute;n por la cual invitamos a revisarlas de manera peri&oacute;dica. <br/><br/>

		<strong>DEFINICIONES:</strong><br/>
		EL USUARIO: Se refiere al identificador &uacute;nico suministrado por el contribuyente o su representante legal al momento de registro en el servicio "Oficina Virtual", consistente de una direcci&oacute;n de correo electr&oacute;nico, el cual concatenado con una contrase&ntilde;a creada por el mismo, servir&aacute; para acceder al servicio y efectuar tr&aacute;mites en nombre del contribuyente, y constituir en lo sucesivo un medio de comunicaci&oacute;n aceptado para su interacci&oacute;n con la Administraci&oacute;n Tributaria Municipal.
		<strong>OFICINA VIRTUAL:</strong> Es el servicio ofrecido por la Administraci&oacute;n Tributaria Municipal constituido por esta p&aacute;gina web y por sistemas inform&aacute;ticos y medios de telecomunicaciones accesorios, que tiene como finalidad la interacci&oacute;n con el usuario de una forma transparente para sus relaciones de car&aacute;cter tributario con EL MUNICIPIO.<br/>
		EL SISTEMA: Se refiere al conjunto de c&oacute;digos y redes inform&aacute;ticos, bases de datos, componentes f&iacute;sicos de c&oacute;mputo, transporte y almacenamiento de datos, y medios de telecomunicaciones accesorios, que permiten la operaci&oacute;n y acceso al registro de contribuyentes que mantiene la Administraci&oacute;n Tributaria Municipal, de acuerdo a lo establecido en el marco legal vigente.<br/>
		<strong>ADMINISTRACION TRIBUTARIA MUNICIPAL:</strong> Se refiere a la Direcci&oacute;n de Rentas Municipales de la Alcald&iacute;a del Municipio Sucre del Estado Miranda, y a todos los entes oficiales o empresas, que de forma accesoria o complementaria act&uacute;an en coordinaci&oacute;n, bajo mandato o por contrato con esta.<br/>
		PAGINA WEB: Es la aplicaci&oacute;n inform&aacute;tica asociada con la direcci&oacute;n &uacute;nica inscrita en los protocolos de Internet (URL), que contiene la informaci&oacute;n general y la capa de acceso a EL SISTEMA sobre el cual opera el servicio "Oficina Virtual" de la Administraci&oacute;n Tributaria Municipal.<br/>
		PAGO EN LINEA: Se refiere al conjunto de operaciones y componentes inform&aacute;ticos que permiten la recaudaci&oacute;n de fondos por parte de instituciones financieras autorizadas por EL MUNICIPIO, provenientes de transacciones relativas al pago de impuestos y tasas generadas en el servicio "Oficina Virtual"<br/>
		EL MUNICIPIO: Se refiere a la Alcald&iacute;a del Municipio Aut&oacute;nomo Sucre del Estado Miranda, sus autoridades y dependencias<br/><br/>

		<strong>CONDICIONES DE USO</strong><br/>
		a)	EL USUARIO entiende y acepta que los datos presentados en esta p&aacute;gina son s&oacute;lo de car&aacute;cter informativo, y pueden presentar diferencias respecto a los movimientos reflejados en estados de cuenta previos o posteriores. Por la naturaleza de la transferencia y compensaci&oacute;n de los archivos electr&oacute;nicos, pueden transcurrir lapsos variables para que los pagos realizados en las instituciones bancarias, el cargo de accesorios, intereses moratorios u otras obligaciones sean mostrados en esta p&aacute;gina. Para realizar reclamos o solicitar correcciones de su Estado de Cuenta u otro documento oficial actualizado, puede visitarnos en nuestras oficinas, ubicadas en la Av. Francisco de Miranda, Urbanizaci&oacute;n Los Dos Caminos, Centro Cvico Plaza Miranda, Nivel PB (frente al Museo de Transporte). Para cualquier consulta referida a este servicio tambi&eacute;n puede comunicarse al 0-800-MISUCRE (08006478273) o a trav&eacute;s del correo atencionalcontribuyenterentas@alcaldiasucre.net <br/><br/>

		b)	EL MUNICIPIO procurar mantener informado al contribuyente sobre los periodos de indisponibilidad del servicio "Oficina Virtual" por mantenimientos programados del sistema o de las redes inform&aacute;ticas, pero el usuario entiende y acepta que ante una indisponibilidad anunciada o no, causada por fallas t&eacute;cnicas, el&eacute;ctricas, de telecomunicaciones, o de otra &iacute;ndole, el contribuyente no quedar&aacute; por este motivo excusado del cumplimiento de sus deberes y obligaciones con la Administraci&oacute;n Tributaria Municipal, dentro de las fechas establecidas en las ordenanzas, decretos u otras normas. En estos casos, puede realizar sus tr&aacute;mites por las taquillas de Atenci&oacute;n al Contribuyente, ubicadas en la direcci&oacute;n anteriormente indicada, o donde lo disponga oportunamente la Direcci&oacute;n de Rentas.<br/><br/>

		c)	Igualmente, el contribuyente entiende y acepta que es de su exclusiva responsabilidad la verificaci&oacute;n de la acreditaci&oacute;n oportuna en su estado de cuenta de las transacciones que efecte bajo la modalidad de "Pago en Linea", y que los reclamos de cualquier naturaleza que puedan surgir a partir de sus transacciones con tarjeta de cr&eacute;dito u otro instrumento de pago en la "Oficina Virtual", deben dirimirlos directamente con la instituci&oacute;n financiera que las procese, sin que la Administraci&oacute;n Tributaria Municipal asuma mayor responsabilidad que suministrar la informaci&oacute;n que posea para que el contribuyente proceda a tal fin.<br/><br/>

		d)	El suministro de toda informaci&oacute;n por parte de los interesados, a trav&eacute;s de esta p&aacute;gina web, se debe regir bajo el Principio de Presunc&oacute;n de Buena Fe consagrado en el Decreto Ley No. 368 sobre Simplificaci&oacute;n de Tr&aacute;mites Administrativos. En consecuencia, en todas las actuaciones que realicen los interesados ante EL MUNICIPIO a trav&eacute;s de este medio, se deben tener como ciertas las declaraciones de &eacute;stos, salvo prueba en contrario.<br/><br/>
		EL MUNICIPIO, a los fines de procurar la mayor confidencialidad posible con relaci&oacute;n a la informaci&oacute;n y datos que suministren los interesados a trav&eacute;s de este medio, advierte que:<br/><br/>
		(a) El uso indebido de la informaci&oacute;n contenida en este sitio, as&iacute; como el suministro de informaci&oacute;n y datos falsos en el curso de las tramitaciones administrativas realizadas a trav&eacute;s de este sitio, acarrear la aplicaci&oacute;n de las sanciones establecidas en la legislaci&oacute;n vigente aplicable a la materia, en especial en la Ley Org&aacute;nica de Salvaguarda del Patrimonio Pblico y/o en el Decreto-Ley sobre Simplificaci&oacute;n de Tr&aacute;mites Administrativos, seg&uacute;n el caso.<br/><br/>
		(b) A los efectos de lo establecido en el art&iacute;culo 63 de la Ley Org&aacute;nica de Salvaguarda del Patrimonio P&uacute;blico, se considera de car&aacute;cter reservado la informaci&oacute;n y datos contenidos en &eacute;ste sitio.<br/><br/>
		A fin de dar cumplimiento a las formalidades establecidas en el art&iacute;culo 49 de la Ley Org&aacute;nica de Procedimientos Administrativos y en los art&iacute;culos 4 y 5 del Reglamento de Registro de Presentaci&oacute;n de Documentos (Decreto No. 1364 de fecha 30 de diciembre de 1981), en el caso de solicitudes o tr&aacute;mites que requieran la presentaci&oacute;n de documentaci&oacute;n los interesados deber&aacute;n imprimir, llenar y firmar (por el representante legal), para luego presentar personalmente ante EL MUNICIPIO o remitirla a &eacute;ste a trav&eacute;s de personas debidamente autorizadas, la solicitud o tr&aacute;mite.<br/><br/>

		<strong>POLÍTICAS DE PRIVACIDAD</strong><br/>
		PRIMERA: EL MUNICIPIO, por medio de la presente Poltica de Privacidad, norma y mantiene debidamente informados a sus usuarios acerca de:<br/> 
		"	Las normas que regulan el suministro, obtenci&oacute;n y uso de la informaci&oacute;n y datos correspondientes a nuestros usuarios; <br/>
		"	La informaci&oacute;n o datos personales que se encuentran en sus registros o archivos; <br/>
		"	El uso que hace EL MUNICIPIO de esa informaci&oacute;n y de esos datos; y <br/>
		"	Si esa informaci&oacute;n o datos son publicados o compartidos en este o cualquier otro medio de comunicaci&oacute;n.<br/> 
		SEGUNDA: Los contribuyentes s&oacute;lo podr&aacute;n acceder a los servicios ofrecidos por EL MUNICIPIO mediante la utilizaci&oacute;n de un USUARIO y contrase&ntilde;a de identificaci&oacute;n, lo cual podr&aacute; requerir un registro previo, y no podr&aacute;n ser accedidos por aquellos usuarios que no est&eacute;n debidamente registrados. <br/>
		TERCERA: EL MUNICIPIO podr&aacute; solicitar directamente la informaci&oacute;n personal del USUARIO, cuando &eacute;ste pretenda registrarse para el uso de alguno de los sistemas que integre los servicios y que as&iacute; lo requiera. 
		CUARTA: Los usuarios que hayan formalizado su registro para cualesquiera de las funcionalidades que ofrezca el servicio "Oficina Virtual", tendr&aacute;n la posibilidad de acceder al servicio, con el objeto de verificar la vigencia de los datos suministrados, actualizarlos cuando as&iacute; les sea requerido, y cualesquiera otras circunstancias que con el tiempo pudieran surgir. <br/>
		Si la modificaci&oacute;n incluye o incorpora informaci&oacute;n o datos falsos, el usuario que incurra en esta conducta se expone a la aplicaci&oacute;n de las sanciones previstas en el Decreto-Ley No. 368 sobre Simplificacin de Trmites Administrativos de fecha 05 de octubre de 1999, publicado en Gaceta Oficial de la Rep&uacute;blica de Venezuela No. 5.393 Extraordinario de fecha 22 de octubre de 1999. <br/>
		QUINTA: EL MUNICIPIO se compromete a no hacer uso de los datos personales de los usuarios, ni de cualquier informaci&oacute;n que le haya sido suministrada por los mismos, para fines distintos a los de la relaci&oacute;n tributaria establecida entre el contribuyente y la Administraci&oacute;n Tributaria Municipal. <br/>
		SEXTA: EL MUNICIPIO har&aacute; uso de informaci&oacute;n personal del usuario para facilitar el acceso; para ayudarlo a encontrar m&aacute;s f&aacute;cilmente servicios o informaci&oacute;n en el servicio "Oficina Virtual", y en general para informarle acerca de aspectos relativos al estado de tramitaci&oacute;n de su declaraci&oacute;n, solicitud o tr&aacute;mite. <br/> 
		SEPTIMA: EL USUARIO acepta enviar a trav&eacute;s del servicio "Oficina Virtual" informaci&oacute;n que considera confidencial, teniendo en cuenta que la Administraci&oacute;n Tributaria Municipal no acepta ni asume obligaci&oacute;n alguna para proteger esa informaci&oacute;n contra divulgaci&oacute;n, que no sea lo dispuesto en la clausula Octava.<br/>
		OCTAVA: EL MUNICIPIO garantiza a los usuarios del servicio "Oficina Virtual" el uso debido de sus datos personales de contacto e informaci&oacute;n tributaria, y su protecci&oacute;n del acceso sin autorizaci&oacute;n o alteraciones. En cumplimiento de esto y de las normas enunciadas en el presente documento, pone al servicio del usuario toda la tecnolog&iacute;a y los avances que se encuentren a su alcance con el fin de asegurar la integridad, respaldo y almacenamiento seguro de la informaci&oacute;n. En algunos casos, al momento del registro del usuario, el sistema realizar preguntas de seguridad que se verificar&aacute;n automticamente contra datos contenidos en documentos tributarios que el contribuyente debe tener en su poder y resguardados adecuadamente, por lo tanto es responsabilidad exclusiva del contribuyente evitar que esa informaci&oacute;n sea manipulada maliciosamente por terceros para obtener acceso no autorizado.<br/>
		NOVENA: INFORMACIN ADICIONAL: Cualquier pregunta o reclamo relacionados con las normas que conforman esta Notificaci&oacute;n de Condiciones de Uso y Pol&iacute;tica de Privacidad, deber&aacute;n ser dirigidas a: Alcalda del Municipio Sucre, Direcci&oacute;n de Rentas Municipales, Oficinas de Atenci&oacute;n al Contribuyente, ubicadas la Av. Francisco de Miranda, Urbanizaci&oacute;n Los Dos Caminos, Centro C&iacute;vico Plaza Miranda, Nivel PB (frente al Museo de Transporte). Para cualquier consulta referida a este servicio tambi&eacute;n puede comunicarse al 0-800-MISUCRE (08006478273) o a trav&eacute;s del correo atencionalcontribuyenterentas@alcaldiasucre.net 


	</p>
	<div>
